# Generated by Django 2.0.13 on 2019-06-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='question_1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
