# Generated by Django 2.0.13 on 2019-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0002_person_question_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailedanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='DetailedQuestion',
        ),
        migrations.RemoveField(
            model_name='multichoiceanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='simplechoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='person',
            name='question_1',
        ),
        migrations.DeleteModel(
            name='DetailedAnswer',
        ),
        migrations.DeleteModel(
            name='MultichoiceAnswer',
        ),
        migrations.DeleteModel(
            name='MultichoiceQuestion',
        ),
        migrations.DeleteModel(
            name='SimpleChoice',
        ),
        migrations.DeleteModel(
            name='SimpleQuestion',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete='CASCADE', to='Questionaire.Question'),
        ),
    ]
