# Generated by Django 2.1.2 on 2018-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0003_auto_20181214_0343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='CreateQuestion',
        ),
    ]
