# Generated by Django 2.0.13 on 2019-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaire', '0005_auto_20190701_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_field',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='persons', to='Questionaire.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete='CASCADE', related_name='choices', to='Questionaire.Question'),
        ),
    ]
